### ISSUE TITLE
Module cannot write to completed_tf_cpc_m49

### ISSUE THREAD

**Issue by sebastian-c** [SWS-Methodology/faoswsTrade#17]
As detailed in SWS-1355:

> When entering the trade data for Bulgaria to Belarus, an error is returned, saying that a code is not present in the table. I checked the list of codes using the dimensionValues api and the code for Belarus is indeed there (see steps to reproduce). However on the web interface (attached), it's clear the Belarus isn't acknowledged as being in the set of valid keys.

```
> complete_trade_flow_cpc[23,]

   geographicAreaM49Reporter geographicAreaM49Partner measuredItemCPC measuredElementTrade timePointYears     Value flagObservationStatus
1:                       100                      112           F1232                 5611           2009 0.2027325                     I
   flagMethod
1:          e

> SaveData("trade","completed_tf_cpc_m49", complete_trade_flow_cpc[23,])

Error in SaveData("trade", "completed_tf_cpc_m49", complete_trade_flow_cpc[23,  : 
  Error while executing SAVE DATA on the SWS Server: org.postgresql.util.PSQLException: ERROR: insert or update on table "session_observation" violates foreign key constraint "session_observation_dim_partner_country_m49_fkey"
  Detail: Key (dim_partner_country_m49)=(56) is not present in table "dim_geographic_m49_trade".
    at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2270)
    at org.postgresql.core.v3.QueryExecutorImpl.processCopyResults(QueryExecutorImpl.java:984)
    at org.postgresql.core.v3.QueryExecutorImpl.endCopy(QueryExecutorImpl.java:846)
    at org.postgresql.core.v3.CopyInImpl.endCopy(CopyInImpl.java:59)
    at org.postgresql.copy.CopyManager.copyIn(CopyManager.java:167)
    at org.postgresql.copy.CopyManager.copyIn(CopyManager.java:146)
    at org.fao.sws.model.dao.impl.ImportDaoImpl$2.doInConnection(ImportDaoImpl.java:746)
    at org.fao.sws.model.dao.impl.ImportDaoImpl$2.doInConnection(ImportDaoImpl.java:739)
    at org.springframework.jdbc.core

> GetCodeList("trade", "completed_tf_cpc_m49", "geographicAreaM49Partner")[code == "112"]

   code description selectionOnly    type  startDate endDate
1:  112     Belarus         FALSE country 1991-01-01      NA
```

![nobelarus](https://cloud.githubusercontent.com/assets/1818581/15609306/9389b048-241f-11e6-9c96-08c0f4b86b95.png)

**Comment by sebastian-c** [comment]
Giorgio just fixed the table. This should be fixed soon.

**Comment by sebastian-c** [comment]
We just had a timeout issue (default timeout is 10 mins). I've set it to 100 minutes and we'll see how that goes.

**Comment by sebastian-c** [comment]
Just had a successful write. The second write said everything was ignored, but it looks like everything has been written.
